useDotenv: true
service: ${env:AWS_LAMBDA_NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-ignore
custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - NODE_ENV
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  memorySize: 128
  region: ${env:AWS_REGION}
  environment:
    NODE_ENV: production
functions:
  app:
    handler: app/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
